#@ load("@ytt:data", "data")

apiVersion: v1
kind: Secret
metadata:
  name: s3-secret-example
  namespace: postgres
type: generic
stringData:
  bucket: #@ data.values.bucket
  region: #@ data.values.region
  endpoint: #@ data.values.endpoint
  key: #@ data.values.key
  keySecret: #@ data.values.secret
  verifyTLS: "false"
